CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --standalone --nnodes=1 --nproc_per_node=4 --master_port=21312 train.py \
    --bs 64 \
    --grad_accumulation_steps 1 \
    --epoch 10 \
    --lr 1e-4 \
    --save_interval 100 \
    --stage image \
    --img_size 256 \
    --n_steps 1000 \
    --min_beta 0.00085 \
    --max_beta 0.012 \
    --beta_schedule scaled_linear \
    --cfg_ratio 0.1 \
    --use_lora \
    --lora_rank 32 \
