CUDA_VISIBLE_DEVICES=0,1,2 torchrun --standalone --nnodes=1 --nproc_per_node=3 --master_port=21312 train.py \
    --bs 3 \
    --grad_accumulation_steps 4 \
    --epoch 10 \
    --lr 1e-5 \
    --save_interval 0.1 \
    --stage expand \
    --num_frames 16 \
    --stride 8 \
    --img_size 256 \
    --n_steps 1000 \
    --min_beta 0.00085 \
    --max_beta 0.012 \
    --beta_schedule scaled_linear \
    --cfg_ratio 0.1 \